<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>index</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <style>
        body {
            overflow-x: hidden;
        }
    </style>
</head>
<body>
    <!--navbar-->
    <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="index.html">Stocked Animal Adoptions</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link" href="index.html">Home</a>
                    <a class="nav-link active" aria-current="page" href="details.html">Contest Winner</a>
                    <a class="nav-link" href="about.html">About</a>
                    <a class="nav-link" href="new-animal-form.html">Animal Form</a>                    
                </div>
            </div>
        </div>
    </nav>
    <!--Title-->
    <h1 class="text-center m-3">Contest Winner!</h1>
    <h6 class="text-center m-3">Congratulations to Zeus, our contest winner!</h3>
    <!--image card-->
    <div class="card h-100" style="max-width:fit-content; margin: 50px;">
        <img src="https://static.wixstatic.com/media/0ad4a1_fac5b71cb1ec4910b6d3f401b7569528~mv2.jpeg/v1/fill/w_1405,h_849,al_c/0ad4a1_fac5b71cb1ec4910b6d3f401b7569528~mv2.jpeg" class="rounded card-img-top" alt="..." style="max-width: 100%; height: auto;">
        <div class="card-body">
            <p class="card-text">Zeus is the winner of our cutest pet contest! He is a black axolotl who has been with us for just under 2 years.</p>
            <p class="card-text">As an axolotl, Zeus enjoys swimming around in his tank and playing with some of his other tank mates. He loves attention from our volunteers, and even tries to eat their fingers when we feed him! We hope that Zeus will come to find a forever home soon. If you wish to adopt him, please give us a call.</p>
            <p class="card-text">For more information on axolotls and their lifestyle, <a href="https://www.axolotlcentral.com/axolotl-care-guide">click here.</a></p>
            <a href="index.html" class="btn btn-primary">Back</a>
        </div>
    </div>
</body>
</html>